steps:
- name: node:10.15.1
  entrypoint: npm
  args: ["install"]
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - "SECRET_KEY=${_SECRET_KEY}"
    - "PORT=${_PORT}"
    - "CLOUD_SQL_CONNECTION=${_CLOUD_SQL_CONNECTION}"
    - "AWS_S3_SECRET_ACCESS_KEY=${_AWS_S3_SECRET_ACCESS_KEY}"
    - "AWS_S3_ACCESS_KEY_ID=${_AWS_S3_ACCESS_KEY_ID}"
    - "PROD_BUCKET_NAME=${_PROD_BUCKET_NAME}"
    - "REAL_ROOT_URL=${_REAL_ROOT_URL}"
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", '--project', 'share-it-server-prod']
